### ISSUE TITLE
Shut down this project?

### ISSUE THREAD

**Issue by breedx2** [flightstats/fava#33]
It appears that this project is probably abandoned.  

Can somebody at FlightStats/Cirium address the status of this repo?  If it is abandoned or should no longer be used or contributed to, can we add a statement to that effect at the top of the project (README)?

Thanks!

**Comment by crozierm** [comment]
Done, after accidentally submitting a PR to jwatson's equally dead repo.

**Comment by breedx2** [comment]
Thanks, @crozierm !
